[package]
name = "migration"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
sea-orm-migration = { version = "1.1.12", features = ["cli"] }
async-std = "1.12"
dotenvy = "0.15"
serde_json = "1.0"

# 🔧 Required for SQLite database support
sea-orm = { version = "1.1", features = ["sqlx-sqlite", "runtime-async-std-native-tls", "with-json"] }

[lib]
name = "migration"
path = "src/lib.rs"

[[bin]]
name = "migration"
path = "src/main.rs"
required-features = ["cli"]

[dev-dependencies]
trybuild = { version = "1", features = ["diff"] }

[features]
cli = []
