name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - name: Install Rustfmt
        run: rustup component add rustfmt
      - name: Run cargo test
        run: cargo test
      - name: Run cargo clippy
        run: cargo clippy -q -- -D warnings
      - name: Install cargo-deny
        run: cargo install cargo-deny --locked
      - name: Run cargo deny
        run: cargo deny check
      - name: Generate module map
        run: |
          git config --global core.autocrlf false
          cargo xtask gen-map --check
