name: Fuzz
on:
  pull_request:
    branches: [ main ]
jobs:
  fuzz:
    if: contains(github.event.pull_request.labels.*.name, 'fuzzing')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz
      - name: Run scroll parser fuzzing
        run: cargo fuzz run scroll_parser -- -max_total_time=60
