name: Nightly Fuzz
on:
  schedule:
    - cron: '0 3 * * 0'
jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz
      - name: Run scroll parser fuzzing
        run: cargo fuzz run scroll_parser -- -max_total_time=300
      - name: Upload crashes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: crash-artifacts
          path: fuzz/artifacts/scroll_parser
