name: Tag Release

on:
  push:
    branches: [main]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: get_version
        run: |
          VERSION=$(grep '^version' scroll_core/Cargo.toml | head -n 1 | sed -E 's/version = "([^"]+)"/\1/')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Create tag
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists"
          else
            git tag "$TAG"
            git push origin "$TAG"
          fi
